name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # 使用自托管的 runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run commands on local device via SSH
        run: |
          ssh -o StrictHostKeyChecking=no nvidia@127.0.0.1 -p 2222 "ls"
